### ISSUE TITLE
not failed npm install

### ISSUE THREAD

**Issue by Muzakie-ID** [nandasafiqalfiansyah/wa-gateway-api#3]
npm warn deprecated puppeteer@13.7.0: < 21.5.0 is no longer supported

> puppeteer@13.7.0 install
> node install.js

/data/data/com.termux/files/home/wa-gateway-api/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26
        throw new Error(message);
              ^

Error: Unsupported platform: android
    at assert (/data/data/com.termux/files/home/wa-gateway-api/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at BrowserFetcher.setPlatform (/data/data/com.termux/files/home/wa-gateway-api/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:184:36)
    at new BrowserFetcher (/data/data/com.termux/files/home/wa-gateway-api/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:168:14)
    at PuppeteerNode.createBrowserFetcher (/data/data/com.termux/files/home/wa-gateway-api/node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js:188:16)
    at downloadBrowser (/data/data/com.termux/files/home/wa-gateway-api/node_modules/puppeteer/lib/cjs/puppeteer/node/install.js:51:46)
    at download (/data/data/com.termux/files/home/wa-gateway-api/node_modules/puppeteer/install.js:86:3)

Node.js v20.17.0
npm error code 1
npm error path /data/data/com.termux/files/home/wa-gateway-api/node_modules/puppeteer
npm error command failed
npm error command sh -c node install.js
npm error A complete log of this run can be found in: /data/data/com.termux/files/home/.npm/_logs/2024-11-30T01_21_03_607Z-debug-0.log
   [ ~/wa-gateway-api ] 

**Comment by Muzakie-ID** [comment]
apa cuma support windows?

**Comment by nandasafiqalfiansyah** [comment]
'NodeJS v12 or higher is required'

**Comment by nandasafiqalfiansyah** [comment]
kalau mau di pakai nanti bisa saya update kalau mau 😊

**Comment by Muzakie-ID** [comment]
mau dipakai dong, btw katanya ada admin dashboard nya

**Comment by nandasafiqalfiansyah** [comment]
owh sebenernya kedepan nya mau saya kasih tapi masih sibuk kerja mas.. hehe

**Comment by Muzakie-ID** [comment]
gas mas tambahin

**Comment by nandasafiqalfiansyah** [comment]
hehe kalau mau **pay** sih ntar aku buatin sampai done..hehe  kalau mau lanjut [wa.me//+628979213614 ](wa.me//+628979213614 )
